[package]
name = "envelope-core"
description = "Generate envelopes with proper address placement"
version = "0.1.0"
authors = ["Jeremy Stucki <dev@jeremystucki.ch>"]
edition = "2018"

[dependencies]
lopdf = "0.26"